"""initial full schema

Revision ID: 0d26806ad448
Revises: 
Create Date: 2026-08-11 22:58:01.130667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0d26806ad448'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_key', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_key', 'version', name='uq_ai_templates_action_version')
    )
    op.create_index(op.f('ix_ai_templates_action_key'), 'ai_templates', ['action_key'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('niveau', sa.Enum('amateur', 'semi_pro', 'pro', name='club_level'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_niveau'), 'clubs', ['niveau'], unique=False)
    op.create_table('formations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_key', sa.String(length=50), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('contexte_utilise', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestion_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statut', sa.Enum('DRAFT', 'READY', 'VIEWED', 'ACCEPTED', 'MODIFIED', 'REJECTED', 'OUTDATED', name='ai_suggestion_statut'), nullable=False),
    sa.Column('pre_generated', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_club_id'), 'ai_suggestions', ['club_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_statut'), 'ai_suggestions', ['statut'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_user_id'), 'ai_suggestions', ['user_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('pending', 'accepted', 'expired', 'revoked', name='invitation_statut'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_club_id'), 'invitations', ['club_id'], unique=False)
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('roles_available_by_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_level', sa.Enum('amateur', 'semi_pro', 'pro', name='club_level'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_level', 'role_id', name='uq_roles_available_by_level')
    )
    op.create_index(op.f('ix_roles_available_by_level_club_level'), 'roles_available_by_level', ['club_level'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'label', name='uq_seasons_club_label')
    )
    op.create_index(op.f('ix_seasons_club_id'), 'seasons', ['club_id'], unique=False)
    op.create_table('staff_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('actif', 'suspendu', 'parti', name='staff_member_statut'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'club_id', name='uq_staff_members_user_club')
    )
    op.create_index(op.f('ix_staff_members_club_id'), 'staff_members', ['club_id'], unique=False)
    op.create_index(op.f('ix_staff_members_user_id'), 'staff_members', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_club_id'), 'teams', ['club_id'], unique=False)
    op.create_table('weighting_matrices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('poste_groupe', sa.Enum('gardien', 'defenseur', 'milieu', 'attaquant', name='poste_groupe'), nullable=False),
    sa.Column('poids_physique', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poids_technique', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poids_tactique', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poids_mental', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'poste_groupe', name='uq_weighting_matrices_club_poste')
    )
    op.create_index(op.f('ix_weighting_matrices_club_id'), 'weighting_matrices', ['club_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ai_suggestion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('modification_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_suggestion_id'], ['ai_suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_ai_suggestion_id'), 'ai_feedback', ['ai_suggestion_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('adversaire', sa.String(length=150), nullable=False),
    sa.Column('competition', sa.String(length=100), nullable=True),
    sa.Column('is_domicile', sa.Boolean(), nullable=False),
    sa.Column('date_match', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('score_equipe', sa.Integer(), nullable=True),
    sa.Column('score_adversaire', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('brouillon', 'programme', 'termine', 'archive', name='match_statut'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_club_id'), 'matches', ['club_id'], unique=False)
    op.create_index(op.f('ix_matches_date_match'), 'matches', ['date_match'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_index(op.f('ix_matches_statut'), 'matches', ['statut'], unique=False)
    op.create_index(op.f('ix_matches_team_id'), 'matches', ['team_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('poste', sa.String(length=50), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('actif', 'blesse', 'suspendu', 'parti', 'archive', name='player_statut'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_club_id'), 'players', ['club_id'], unique=False)
    op.create_index(op.f('ix_players_statut'), 'players', ['statut'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('date_seance', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('objectifs', sa.Text(), nullable=True),
    sa.Column('exercices', sa.Text(), nullable=True),
    sa.Column('charge_prevue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.Enum('planifiee', 'realisee', 'annulee', name='training_statut'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_club_id'), 'training_sessions', ['club_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_date_seance'), 'training_sessions', ['date_seance'], unique=False)
    op.create_index(op.f('ix_training_sessions_statut'), 'training_sessions', ['statut'], unique=False)
    op.create_index(op.f('ix_training_sessions_team_id'), 'training_sessions', ['team_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_member_id', 'permission_id', name='uq_user_permissions')
    )
    op.create_index(op.f('ix_user_permissions_staff_member_id'), 'user_permissions', ['staff_member_id'], unique=False)
    op.create_table('work_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('hebdomadaire', 'mensuel', name='work_plan_type'), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_plans_club_id'), 'work_plans', ['club_id'], unique=False)
    op.create_index(op.f('ix_work_plans_team_id'), 'work_plans', ['team_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('note_globale', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('poids_physique_utilise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('poids_technique_utilise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('poids_tactique_utilise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('poids_mental_utilise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('saisie_hors_ligne', sa.Boolean(), nullable=False),
    sa.Column('synchronisee', sa.Boolean(), nullable=False),
    sa.Column('contexte_saisie', sa.Enum('direct_stade', 'apres_match', 'avant_entrainement', 'apres_entrainement', 'planification', 'autre', name='contexte_saisie'), nullable=False),
    sa.Column('date_saisie_reelle', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_creation_en_base', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_evaluations_match_player')
    )
    op.create_index(op.f('ix_evaluations_match_id'), 'evaluations', ['match_id'], unique=False)
    op.create_index(op.f('ix_evaluations_player_id'), 'evaluations', ['player_id'], unique=False)
    op.create_table('match_tactical_setups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=True),
    sa.Column('formation_label', sa.String(length=50), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'valide', name='lineup_statut'), nullable=False),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_tactical_setups_match_id'), 'match_tactical_setups', ['match_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_player_id'), 'medical_records', ['player_id'], unique=False)
    op.create_table('physical_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('taille_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('poids_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('imc', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('charge_travail', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('substitutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_out_id', sa.Integer(), nullable=False),
    sa.Column('player_in_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('motif', sa.Enum('tactique', 'blessure', 'fatigue', 'sanction', 'autre', name='substitution_motif'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_in_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substitutions_match_id'), 'substitutions', ['match_id'], unique=False)
    op.create_index(op.f('ix_substitutions_player_in_id'), 'substitutions', ['player_in_id'], unique=False)
    op.create_index(op.f('ix_substitutions_player_out_id'), 'substitutions', ['player_out_id'], unique=False)
    op.create_table('training_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('assiduite', sa.Enum('present', 'absent', 'retard', name='assiduite'), nullable=False),
    sa.Column('charge_percue_rpe', sa.Integer(), nullable=True),
    sa.Column('saisie_hors_ligne', sa.Boolean(), nullable=False),
    sa.Column('synchronisee', sa.Boolean(), nullable=False),
    sa.Column('contexte_saisie', sa.Enum('direct_stade', 'apres_match', 'avant_entrainement', 'apres_entrainement', 'planification', 'autre', name='contexte_saisie'), nullable=False),
    sa.Column('date_saisie_reelle', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_creation_en_base', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('charge_percue_rpe IS NULL OR (charge_percue_rpe >= 1 AND charge_percue_rpe <= 10)', name='ck_training_evaluations_rpe'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_evaluations_player_id'), 'training_evaluations', ['player_id'], unique=False)
    op.create_index(op.f('ix_training_evaluations_training_session_id'), 'training_evaluations', ['training_session_id'], unique=False)
    op.create_table('work_plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_plan_id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('objectifs', sa.Text(), nullable=True),
    sa.Column('statut_prevu', sa.String(length=30), nullable=True),
    sa.Column('statut_reel', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_plan_items_training_session_id'), 'work_plan_items', ['training_session_id'], unique=False)
    op.create_index(op.f('ix_work_plan_items_work_plan_id'), 'work_plan_items', ['work_plan_id'], unique=False)
    op.create_table('lineup_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_tactical_setup_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_starting', sa.Boolean(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_goalkeeper', sa.Boolean(), nullable=False),
    sa.Column('tactical_role', sa.String(length=50), nullable=True),
    sa.Column('position_x', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('position_y', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('substitute_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position_x >= 0 AND position_x <= 100', name='ck_lineup_players_x'),
    sa.CheckConstraint('position_y >= 0 AND position_y <= 100', name='ck_lineup_players_y'),
    sa.ForeignKeyConstraint(['match_tactical_setup_id'], ['match_tactical_setups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineup_players_match_tactical_setup_id'), 'lineup_players', ['match_tactical_setup_id'], unique=False)
    op.create_index(op.f('ix_lineup_players_player_id'), 'lineup_players', ['player_id'], unique=False)
    op.create_table('match_evaluation_pillars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('pilier', sa.Enum('physique', 'technique', 'tactique', 'mental', name='pilier'), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('note >= 0 AND note <= 10', name='ck_match_eval_pillars_note'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'pilier', name='uq_match_eval_pillar')
    )
    op.create_index(op.f('ix_match_evaluation_pillars_evaluation_id'), 'match_evaluation_pillars', ['evaluation_id'], unique=False)
    op.create_table('training_evaluation_pillars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_evaluation_id', sa.Integer(), nullable=False),
    sa.Column('pilier', sa.Enum('physique', 'technique', 'tactique', 'mental', name='pilier'), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('note >= 0 AND note <= 10', name='ck_training_eval_pillars_note'),
    sa.ForeignKeyConstraint(['training_evaluation_id'], ['training_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_evaluation_id', 'pilier', name='uq_training_eval_pillar')
    )
    op.create_index(op.f('ix_training_evaluation_pillars_training_evaluation_id'), 'training_evaluation_pillars', ['training_evaluation_id'], unique=False)
    op.create_table('weighting_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('poste_groupe', sa.Enum('gardien', 'defenseur', 'milieu', 'attaquant', name='poste_groupe'), nullable=False),
    sa.Column('poids_physique', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poids_technique', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poids_tactique', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('poids_mental', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', name='uq_weighting_snapshots_evaluation')
    )
    op.create_index(op.f('ix_weighting_snapshots_evaluation_id'), 'weighting_snapshots', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weighting_snapshots_evaluation_id'), table_name='weighting_snapshots')
    op.drop_table('weighting_snapshots')
    op.drop_index(op.f('ix_training_evaluation_pillars_training_evaluation_id'), table_name='training_evaluation_pillars')
    op.drop_table('training_evaluation_pillars')
    op.drop_index(op.f('ix_match_evaluation_pillars_evaluation_id'), table_name='match_evaluation_pillars')
    op.drop_table('match_evaluation_pillars')
    op.drop_index(op.f('ix_lineup_players_player_id'), table_name='lineup_players')
    op.drop_index(op.f('ix_lineup_players_match_tactical_setup_id'), table_name='lineup_players')
    op.drop_table('lineup_players')
    op.drop_index(op.f('ix_work_plan_items_work_plan_id'), table_name='work_plan_items')
    op.drop_index(op.f('ix_work_plan_items_training_session_id'), table_name='work_plan_items')
    op.drop_table('work_plan_items')
    op.drop_index(op.f('ix_training_evaluations_training_session_id'), table_name='training_evaluations')
    op.drop_index(op.f('ix_training_evaluations_player_id'), table_name='training_evaluations')
    op.drop_table('training_evaluations')
    op.drop_index(op.f('ix_substitutions_player_out_id'), table_name='substitutions')
    op.drop_index(op.f('ix_substitutions_player_in_id'), table_name='substitutions')
    op.drop_index(op.f('ix_substitutions_match_id'), table_name='substitutions')
    op.drop_table('substitutions')
    op.drop_table('physical_profiles')
    op.drop_index(op.f('ix_medical_records_player_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_match_tactical_setups_match_id'), table_name='match_tactical_setups')
    op.drop_table('match_tactical_setups')
    op.drop_index(op.f('ix_evaluations_player_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_match_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_work_plans_team_id'), table_name='work_plans')
    op.drop_index(op.f('ix_work_plans_club_id'), table_name='work_plans')
    op.drop_table('work_plans')
    op.drop_index(op.f('ix_user_permissions_staff_member_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_training_sessions_team_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_statut'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_date_seance'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_club_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_statut'), table_name='players')
    op.drop_index(op.f('ix_players_club_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_statut'), table_name='matches')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_date_match'), table_name='matches')
    op.drop_index(op.f('ix_matches_club_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_ai_feedback_ai_suggestion_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_weighting_matrices_club_id'), table_name='weighting_matrices')
    op.drop_table('weighting_matrices')
    op.drop_index(op.f('ix_teams_club_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_staff_members_user_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_club_id'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_seasons_club_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_roles_available_by_level_club_level'), table_name='roles_available_by_level')
    op.drop_table('roles_available_by_level')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_club_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_ai_suggestions_user_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_statut'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_club_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('formations')
    op.drop_index(op.f('ix_clubs_niveau'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_ai_templates_action_key'), table_name='ai_templates')
    op.drop_table('ai_templates')
    # ### end Alembic commands ###
