"""add ai module

Revision ID: 97c8bf6a4e60
Revises: dbd57c83f186
Create Date: 2026-08-12 00:34:12.631297

"""
from alembic import op
import sqlalchemy as sa


revision = '97c8bf6a4e60'
down_revision = 'dbd57c83f186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
