"""add training and planning

Revision ID: b3ea619cf3d0
Revises: 0d26806ad448
Create Date: 2026-08-11 23:19:25.010097

"""
from alembic import op
import sqlalchemy as sa


revision = 'b3ea619cf3d0'
down_revision = '0d26806ad448'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
