"""add uploaded files

Revision ID: b806a273afbe
Revises: 97c8bf6a4e60
Create Date: 2026-08-12 02:43:05.873705

"""
from alembic import op
import sqlalchemy as sa


revision = 'b806a273afbe'
down_revision = '97c8bf6a4e60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'txt', 'docx', 'jpeg', 'png', name='file_type'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=30), nullable=True),
    sa.Column('context_id', sa.BigInteger(), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_club_id'), 'uploaded_files', ['club_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_uploaded_by'), 'uploaded_files', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_uploaded_by'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_club_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
