"""add ai module

Revision ID: dbd57c83f186
Revises: fbcb327cba70
Create Date: 2026-08-12 00:14:04.948877

"""
from alembic import op
import sqlalchemy as sa


revision = 'dbd57c83f186'
down_revision = 'fbcb327cba70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
