"""add evaluations and weighting

Revision ID: fbcb327cba70
Revises: b3ea619cf3d0
Create Date: 2026-08-11 23:44:28.530528

"""
from alembic import op
import sqlalchemy as sa


revision = 'fbcb327cba70'
down_revision = 'b3ea619cf3d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
