"""add auth refresh tokens

Revision ID: 3c30bcb7cfaa
Revises: 990b4b747714
Create Date: 2026-08-11 03:52:33.378522

"""
from alembic import op
import sqlalchemy as sa


revision = '3c30bcb7cfaa'
down_revision = '990b4b747714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
