"""add ai module

Revision ID: a473fc139bef
Revises: eeb3a0cde242
Create Date: 2026-08-11 18:52:53.306189

"""
from alembic import op
import sqlalchemy as sa


revision = 'a473fc139bef'
down_revision = 'eeb3a0cde242'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
