"""add ai tables

Revision ID: f6c4f7ba8c74
Revises: a473fc139bef
Create Date: 2026-08-11 21:38:16.783631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f6c4f7ba8c74'
down_revision = 'a473fc139bef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_key', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_key', 'version', name='uq_ai_templates_action_version')
    )
    op.create_index(op.f('ix_ai_templates_action_key'), 'ai_templates', ['action_key'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_key', sa.String(length=50), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('contexte_utilise', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestion_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statut', sa.Enum('DRAFT', 'READY', 'VIEWED', 'ACCEPTED', 'MODIFIED', 'REJECTED', 'OUTDATED', name='ai_suggestion_statut'), nullable=False),
    sa.Column('pre_generated', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_club_id'), 'ai_suggestions', ['club_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_statut'), 'ai_suggestions', ['statut'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_user_id'), 'ai_suggestions', ['user_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ai_suggestion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('modification_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_suggestion_id'], ['ai_suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_ai_suggestion_id'), 'ai_feedback', ['ai_suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedback_ai_suggestion_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_ai_suggestions_user_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_statut'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_club_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index(op.f('ix_ai_templates_action_key'), table_name='ai_templates')
    op.drop_table('ai_templates')
    # ### end Alembic commands ###
